### ISSUE TITLE
fortschritt does not specify license information

### ISSUE THREAD

**Issue by fwolfst** [xijo/fortschritt#4]
Neither `.gemspec` nor `README` nor `LICENSE`/`COPYING` specify that fortschritt is `GPLv3+` licensed (or any other license ;) ).

https://github.com/fwolfst/your-repository/issues/3

**Comment by xijo** [comment]
Very true, that cannot stand. I hereby proclaim this gem licensed under WTFPL! 

Release 1.0.0, to duly celebrate this special occasion! :trollface:
